#!/bin/bash

# CDDL HEADER START
#
# This file and its contents are supplied under the terms of the
# Common Development and Distribution License ("CDDL"), version 1.0.
# You may only use this file in accordance with the terms of version
# 1.0 of the CDDL.
#
# A full copy of the text of the CDDL should have accompanied this
# source.  A copy of the CDDL is also available via the Internet at
# http://www.illumos.org/license/CDDL.
#
# CDDL HEADER END

# Copyright 2016 Saso Kiselkov. All rights reserved.

FREETYPE="freetype-2.7.tar.gz"
FREETYPE_BUILDDIR="${FREETYPE/%.tar.gz/}"

function build_freetype() {
	PLATFORM="$1"
	CONFOPTS="$2"
	CFLAGS="$3"
	LDFLAGS="$4"

	if ! [ -d "$FREETYPE_BUILDDIR" ]; then
		tar -C "$(dirname "$FREETYPE_BUILDDIR")" -xzf "$FREETYPE" || \
		    exit 1
	fi
	if [ -f "freetype-$PLATFORM/lib/libfreetype.a" ] && \
	    [ "freetype-$PLATFORM/lib/libfreetype.a" -nt "$FREETYPE" ]; then
		return
	fi
	(
		cd "$FREETYPE_BUILDDIR"
		make distclean || exit 1
		rm -rf "$(pwd)/../freetype-$PLATFORM"
		# Linux: for some reason, we need to specify an optimization
		# level or we won't get lstat/fstat correctly defined. WTF...
		CFLAGS="${CFLAGS} -fvisibility=hidden -O2" \
		LDFLAGS="${LDFLAGS} -fvisibility=hidden" \
		    ./configure \
		    --prefix="$(pwd)/../freetype-$PLATFORM" $CONFOPTS \
		    --disable-shared --enable-static --with-zlib=no \
		    --with-bzip2=no --with-png=no --with-harfbuzz=no \
		    --with-old-mac-fonts=no --with-fsspec=no \
		    --with-fsref=no --with-quickdraw-toolbox=no \
		    --with-quickdraw-carbon=no --with-ats=no || exit 1
		make -j $NCPUS || exit 1
		make install || exit 1
	)
}

case `uname` in
	Linux)
		NCPUS=$(( $(grep 'processor[[:space:]]\+:' /proc/cpuinfo \
		    | wc -l) + 1 ))
		build_freetype "linux-64" "" "-fPIC" "-fPIC"
		build_freetype "linux-32" "" "-m32 -fPIC -fno-stack-protector" \
		    "-m32 -fPIC"
		build_freetype "win-64" "--host=x86_64-w64-mingw32"
		build_freetype "win-32" "--host=i686-w64-mingw32"
		;;
	Darwin)
		NCPUS=$(( $(sysctl -n hw.ncpu) + 1 ))
		build_freetype "mac-64"
		build_freetype "mac-32" "" "-m32" "-m32"
		;;
	*)
		echo "Unsupported build platform" >&2
		exit 1
		;;
esac
